AllCops:
  TargetRubyVersion: 3.X
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Sample:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false
